<?php

$results = [
    [
        "RKEY" => "881929",
        "TITULO" => "ABC DEL AIRE ACONDICIONADO",
        "TIPO" => "Libro electrónico",
        "RECURSO" => "TECNMALFA",
        "URL" => "https://demo.com/read/9786076224786/index",
        "NIVELES" => "*Superior*",
        "TEMAS" => "",
        "AREAS" => "*ING. ELECTRICA ELECTRONICA*",
        "AUTOR" => "MIRANDA",
        "EDITORIAL" => "Alfaomega / Marcombo",
        "KEY_PROVEEDORES" => "143",
        "KEY_TIPOS" => "8",
        "FORMATO" => "digital",
        "PORTADA" => "ALFA9786076224786.jpg",
        "ISBN_ISSN" => "9786076224786",
        "EDICION" => "",
        "IMG" => "http://demo.mx/imgs/tablet.png",
        "TITULOMOD" => "ABC DEL AIRE ACONDICIONADO",
        "ENUM" => 1,
    ],
    [
        "RKEY" => "881924",
        "TITULO" => "AGRICULTURA, GANADERIA, SILVICULTURA Y PESCA - Régimen fiscal",
        "TIPO" => "Libro electrónico",
        "RECURSO" => "TECNMALFA",
        "URL" => "https://demo.com/read/9786076293584/index",
        "NIVELES" => "*Superior*",
        "TEMAS" => "*Contabilidad*",
        "AREAS" => "*Negocios y Economía*",
        "AUTOR" => "PEREZ CHAVEZ, José ; FOL OLGUIN, Raymundo",
        "EDITORIAL" => "TAX Editores",
        "KEY_PROVEEDORES" => "143",
        "KEY_TIPOS" => "8",
        "FORMATO" => "digital",
        "PORTADA" => "ALFAAGRICULTURA.jpg",
        "ISBN_ISSN" => "9786076293584",
        "EDICION" => "",
        "IMG" => "http://demo.mx/imgs/tablet.png",
        "TITULOMOD" => "AGRICULTURA, GANADERIA, SILVICULTURA Y PESCA - Régimen fiscal",
        "ENUM" => 2,
    ],
    [
        "RKEY" => "881930",
        "TITULO" => "AGUA Fuentes, caracterización, tecnología y gestión sustentable",
        "TIPO" => "Libro electrónico",
        "RECURSO" => "TECNMALFA",
        "URL" => "https://demo.com/read/9786076228920/index",
        "NIVELES" => "*Superior*",
        "TEMAS" => "",
        "AREAS" => "*ING. ELECTRICA ELECTRONICA*",
        "AUTOR" => "VEGA",
        "EDITORIAL" => "Alfaomega",
        "KEY_PROVEEDORES" => "143",
        "KEY_TIPOS" => "8",
        "FORMATO" => "digital",
        "PORTADA" => "ALFA9786076228920.jpg",
        "ISBN_ISSN" => "9786076228920",
        "EDICION" => "",
        "IMG" => "http://demo.mx/imgs/tablet.png",
        "TITULOMOD" => "AGUA Fuentes, caracterización, tecnología y gestión sustentable",
        "ENUM" => 3,
    ],
    [
        "RKEY" => "881931",
        "TITULO" => "ALGORITMOS GENÉTICOS CON PYTHON",
        "TIPO" => "Libro electrónico",
        "RECURSO" => "TECNMALFA",
        "URL" => "https://demo.com/read/9786075387154/index",
        "NIVELES" => "*Superior*",
        "TEMAS" => "",
        "AREAS" => "*Computación*",
        "AUTOR" => "GUTIÉRREZ REINA, Daniel; TAPIA CÓRDOBA, Alejandro",
        "EDITORIAL" => "Alfaomega / Marcombo",
        "KEY_PROVEEDORES" => "143",
        "KEY_TIPOS" => "8",
        "FORMATO" => "digital",
        "PORTADA" => "alfaalgoritmos.jpg",
        "ISBN_ISSN" => "9786075387154",
        "EDICION" => "",
        "IMG" => "http://demo.mx/imgs/tablet.png",
        "TITULOMOD" => "ALGORITMOS GENETICOS CON PYTHON",
        "ENUM" => 4,
    ],
    [
        "RKEY" => "881932",
        "TITULO" => "ANÁLISIS DE ESTRUCTURAS - Métodos clásico y matricial 4ª Edición",
        "TIPO" => "Libro electrónico",
        "RECURSO" => "TECNMALFA",
        "URL" => "https://demo.com/read/9786077072911/index",
        "NIVELES" => "*Superior*",
        "TEMAS" => "",
        "AREAS" => "*ING. ELECTRICA ELECTRONICA*",
        "AUTOR" => "MCCORMAC, Jack",
        "EDITORIAL" => "Alfaomega",
        "KEY_PROVEEDORES" => "143",
        "KEY_TIPOS" => "8",
        "FORMATO" => "digital",
        "PORTADA" => "ALFA9786077072911.jpg",
        "ISBN_ISSN" => "9786077072911",
        "EDICION" => "",
        "IMG" => "http://demo.mx/imgs/tablet.png",
        "TITULOMOD" => "ANALISIS DE ESTRUCTURAS - Métodos clásico y matricial 4ª Edición",
        "ENUM" => 5,
    ],
];

header('Content-Type: application/json');

echo json_encode($results);